sudo: false
language: android
jdk: oraclejdk8

env:
  - ANDROID_TARGET=25 BUILD_TOOLS=25.0.2

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25+, latest, cannot get more granular control than this
    # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943 for more
    # details.
    - platform-tools #latest
    - "build-tools-$BUILD_TOOLS"
    - "android-$ANDROID_TARGET"
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - "addon-google_apis-google-$ANDROID_TARGET"


before_install:
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

licenses:
  - 'android-sdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew lint check jacocoTestReport
  # building remixer_example:assembleRelease will fail explicitly if proguarding is broken.
  - ./gradlew remixer_example:assembleRelease

after_success:
  - bash <(curl -s https://codecov.io/bash)
